pipeline{
    agent any
    tools{
        maven 'maven'
    
    }
    environment{
        HOME_SONAR = tool(scanner)
    }
    stages{
        stage('Checkout Code') {
            steps {
                git branch: 'feature', url: 'https://github.com/dockersamples/example-voting-app.git'
            }
        }
        stage(" test static code analysist"){
            steps{
                withSonarQubeEnv('sonar') {
                  sh '''
                    $HOME_SONAR/bin/scanner -Dsonar.projectName = "voteapp" \n
                    -Dsonar.projectKey = "voteapp"
                    '''
                    }

                
                   }

                    }
        stage("wait for qulity gate"){
            steps{
                script{
                    test = waitForQualityGate()
                    if ($test.status != 'ok'){
                         error "Pipeline failed due to SonarQube Quality Gate failure: ${qg.status}"
                    }
                }
            }
        }
        stage("trivy check"){
            steps{
                sh ' trivy --fs --severity HIGH,CRITICAL --exit-code 1 chumaedeogu/vote:${build_number}'
            }
        }
        stage("build docker file"){
     
            steps{
                sh ' docker build -t chumaedeogu/vote:${build_number} .'
            }
        }
        stage("trivy check"){
            steps{
                sh ' trivy --image --severity HIGH,CRITICAL --exit-code 1 chumaedeogu/vote:${build_number}'
            }
        }

    }
}
